
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/database_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true

  databaseApp:
    default.admin.pass: ${DEFAULT_ADMIN_PASS:topsecret}
    remember.me.key: ${REMEMBER_ME_KEY:topsecret}





servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

#server:
#    port: 8080